module ApplicationHelper
	
	def default_statuses
		['not submitted', 'sent for approval', 'requires revision', 'approved']
	end

	def countries_list
		[
			"Andorra",
			"Afghanistan",
			"Albania",
			"Algeria",
			"American Samoa",
			"Angola",
			"Anguilla",
			"Antarctica",
			"Antigua and Barbuda",
			"Argentina",
			"Armenia",
			"Aruba",
			"Australia",
			"Austria",
			"Azerbaijan",
			"Bahamas, The",
			"Bahrain",
			"Bangladesh",
			"Barbados",
			"Belarus",
			"Belgium",
			"Belize",
			"Benin",
			"Bermuda",
			"Bhutan",
			"Bolivia",
			"Bosnia and Herzegovina",
			"Botswana",
			"Bouvet Island",
			"Brazil",
			"British Indian Ocean Territory",
			"British Virgin Islands",
			"Brunei",
			"Bulgaria",
			"Burkina Faso",
			"Burma",
			"Burundi",
			"Cambodia",
			"Cameroon",
			"Canada",
			"Cape Verde",
			"Cayman Islands",
			"Central African Republic",
			"Chad",
			"Chile",
			"China",
			"Christmas Island",
			"Cocos (Keeling) Islands",
			"Colombia",
			"Comoros",
			"Congo, Democratic Republic of the",
			"Congo, Republic of the",
			"Cook Islands",
			"Costa Rica",
			"Cote d'Ivoire",
			"Croatia",
			"Cuba",
			"Curacao",
			"Cyprus",
			"Czech Republic",
			"Denmark",
			"Djibouti",
			"Dominica",
			"Dominican Republic",
			"Ecuador",
			"Egypt",
			"El Salvador",
			"Equatorial Guinea",
			"Eritrea",
			"Estonia",
			"Ethiopia",
			"Falkland Islands (Islas Malvinas)",
			"Faroe Islands",
			"Fiji",
			"Finland",
			"France",
			"France, Metropolitan",
			"French Guiana",
			"French Polynesia",
			"French Southern and Antarctic Lands",
			"Gabon",
			"Gambia, The",
			"Gaza Strip",
			"Georgia",
			"Germany",
			"Ghana",
			"Gibraltar",
			"Greece",
			"Greenland",
			"Grenada",
			"Guadeloupe",
			"Guam",
			"Guatemala",
			"Guernsey",
			"Guiissau",
			"Guinea",
			"Guyana",
			"Haiti",
			"Heard Island and McDonald Islands",
			"Holy See (Vatican City)",
			"Honduras",
			"Hong Kong",
			"Hungary",
			"Iceland",
			"India",
			"Indonesia",
			"Iran",
			"Iraq",
			"Ireland",
			"Isle of Man",
			"Israel",
			"Italy",
			"Jamaica",
			"Japan",
			"Jersey",
			"Jordan",
			"Kazakhstan",
			"Kenya",
			"Kiribati",
			"Korea, North",
			"Korea, South",
			"Kosovo",
			"Kuwait",
			"Kyrgyzstan",
			"Laos",
			"Latvia",
			"Lebanon",
			"Lesotho",
			"Liberia",
			"Libya",
			"Liechtenstein",
			"Lithuania",
			"Luxembourg",
			"Macau",
			"Macedonia",
			"Madagascar",
			"Malawi",
			"Malaysia",
			"Maldives",
			"Mali",
			"Malta",
			"Marshall Islands",
			"Martinique",
			"Mauritania",
			"Mauritius",
			"Mayotte",
			"Mexico",
			"Micronesia, Federated States of",
			"Moldova",
			"Monaco",
			"Mongolia",
			"Montenegro",
			"Montserrat",
			"Morocco",
			"Mozambique",
			"Namibia",
			"Nauru",
			"Nepal",
			"Netherlands",
			"New Caledonia",
			"New Zealand",
			"Nicaragua",
			"Niger",
			"Nigeria",
			"Niue",
			"Norfolk Island",
			"Northern Mariana Islands",
			"Norway",
			"Oman",
			"Pakistan",
			"Palau",
			"Panama",
			"Papua New Guinea",
			"Paraguay",
			"Peru",
			"Philippines",
			"Pitcairn Islands",
			"Poland",
			"Portugal",
			"Puerto Rico",
			"Qatar",
			"Reunion",
			"Romania",
			"Russia",
			"Rwanda",
			"Saint Barthelemy",
			"Saint Helena, Ascension, and Tristan da Cunha",
			"Saint Kitts and Nevis",
			"Saint Lucia",
			"Saint Martin",
			"Saint Pierre and Miquelon",
			"Saint Vincent and the Grenadines",
			"Samoa",
			"San Marino",
			"Sao Tome and Principe",
			"Saudi Arabia",
			"Senegal",
			"Serbia",
			"Seychelles",
			"Sierra Leone",
			"Singapore",
			"Sint Maarten",
			"Slovakia",
			"Slovenia",
			"Solomon Islands",
			"Somalia",
			"South Africa",
			"South Georgia and the Islands",
			"South Sudan",
			"Spain",
			"Sri Lanka",
			"Sudan",
			"Suriname",
			"Svalbard",
			"Swaziland",
			"Sweden",
			"Switzerland",
			"Syria",
			"Taiwan",
			"Tajikistan",
			"Tanzania",
			"Thailand",
			"Tieste",
			"Togo",
			"Tokelau",
			"Tonga",
			"Trinidad and Tobago",
			"Tunisia",
			"Turkey",
			"Turkmenistan",
			"Turks and Caicos Islands",
			"Tuvalu",
			"Uganda",
			"Ukraine",
			"United Arab Emirates",
			"United Kingdom",
			"United States",
			"United States Minor Outlying Islands",
			"Uruguay",
			"Uzbekistan",
			"Vanuatu",
			"Venezuela",
			"Vietnam",
			"Virgin Islands",
			"Wallis and Futuna",
			"West Bank",
			"Western Sahara",
			"Yemen",
			"Zambia",
			"Zimbabwe"
		]
	end

	def currencies_list
		[
			"AED - United Arab Emirates Dirham",
			"AFN - Afghanistan Afghani",
			"ALL - Albania Lek",
			"AMD - Armenia Dram",
			"ANG - Netherlands Antilles Guilder",
			"AOA - Angola Kwanza",
			"ARS - Argentina Peso",
			"AUD - Australia Dollar",
			"AWG - Aruba Guilder",
			"AZN - Azerbaijan New Manat",
			"BAM - Bosnia and Herzegovina Convertible Marka",
			"BBD - Barbados Dollar",
			"BDT - Bangladesh Taka",
			"BGN - Bulgaria Lev",
			"BHD - Bahrain Dinar",
			"BIF - Burundi Franc",
			"BMD - Bermuda Dollar",
			"BND - Brunei Darussalam Dollar",
			"BOB - Bolivia Bolíviano",
			"BRL - Brazil Real",
			"BSD - Bahamas Dollar",
			"BTN - Bhutan Ngultrum",
			"BWP - Botswana Pula",
			"BYR - Belarus Ruble",
			"BZD - Belize Dollar",
			"CAD - Canada Dollar",
			"CDF - Congo/Kinshasa Franc",
			"CHF - Switzerland Franc",
			"CLP - Chile Peso",
			"CNY - China Yuan Renminbi",
			"COP - Colombia Peso",
			"CRC - Costa Rica Colon",
			"CUC - Cuba Convertible Peso",
			"CUP - Cuba Peso",
			"CVE - Cape Verde Escudo",
			"CZK - Czech Republic Koruna",
			"DJF - Djibouti Franc",
			"DKK - Denmark Krone",
			"DOP - Dominican Republic Peso",
			"DZD - Algeria Dinar",
			"EGP - Egypt Pound",
			"ERN - Eritrea Nakfa",
			"ETB - Ethiopia Birr",
			"EUR - Euro Member Countries",
			"FJD - Fiji Dollar",
			"FKP - Falkland Islands (Malvinas) Pound",
			"GBP - United Kingdom Pound",
			"GEL - Georgia Lari",
			"GGP - Guernsey Pound",
			"GHS - Ghana Cedi",
			"GIP - Gibraltar Pound",
			"GMD - Gambia Dalasi",
			"GNF - Guinea Franc",
			"GTQ - Guatemala Quetzal",
			"GYD - Guyana Dollar",
			"HKD - Hong Kong Dollar",
			"HNL - Honduras Lempira",
			"HRK - Croatia Kuna",
			"HTG - Haiti Gourde",
			"HUF - Hungary Forint",
			"IDR - Indonesia Rupiah",
			"ILS - Israel Shekel",
			"IMP - Isle of Man Pound",
			"INR - India Rupee",
			"IQD - Iraq Dinar",
			"IRR - Iran Rial",
			"ISK - Iceland Krona",
			"JEP - Jersey Pound",
			"JMD - Jamaica Dollar",
			"JOD - Jordan Dinar",
			"JPY - Japan Yen",
			"KES - Kenya Shilling",
			"KGS - Kyrgyzstan Som",
			"KHR - Cambodia Riel",
			"KMF - Comoros Franc",
			"KPW - Korea (North) Won",
			"KRW - Korea (South) Won",
			"KWD - Kuwait Dinar",
			"KYD - Cayman Islands Dollar",
			"KZT - Kazakhstan Tenge",
			"LAK - Laos Kip",
			"LBP - Lebanon Pound",
			"LKR - Sri Lanka Rupee",
			"LRD - Liberia Dollar",
			"LSL - Lesotho Loti",
			"LYD - Libya Dinar",
			"MAD - Morocco Dirham",
			"MDL - Moldova Leu",
			"MGA - Madagascar Ariary",
			"MKD - Macedonia Denar",
			"MMK - Myanmar (Burma) Kyat",
			"MNT - Mongolia Tughrik",
			"MOP - Macau Pataca",
			"MRO - Mauritania Ouguiya",
			"MUR - Mauritius Rupee",
			"MVR - Maldives (Maldive Islands) Rufiyaa",
			"MWK - Malawi Kwacha",
			"MXN - Mexico Peso",
			"MYR - Malaysia Ringgit",
			"MZN - Mozambique Metical",
			"NAD - Namibia Dollar",
			"NGN - Nigeria Naira",
			"NIO - Nicaragua Cordoba",
			"NOK - Norway Krone",
			"NPR - Nepal Rupee",
			"NZD - New Zealand Dollar",
			"OMR - Oman Rial",
			"PAB - Panama Balboa",
			"PEN - Peru Sol",
			"PGK - Papua New Guinea Kina",
			"PHP - Philippines Peso",
			"PKR - Pakistan Rupee",
			"PLN - Poland Zloty",
			"PYG - Paraguay Guarani",
			"QAR - Qatar Riyal",
			"RON - Romania New Leu",
			"RSD - Serbia Dinar",
			"RUB - Russia Ruble",
			"RWF - Rwanda Franc",
			"SAR - Saudi Arabia Riyal",
			"SBD - Solomon Islands Dollar",
			"SCR - Seychelles Rupee",
			"SDG - Sudan Pound",
			"SEK - Sweden Krona",
			"SGD - Singapore Dollar",
			"SHP - Saint Helena Pound",
			"SLL - Sierra Leone Leone",
			"SOS - Somalia Shilling",
			"SPL - Seborga Luigino",
			"SRD - Suriname Dollar",
			"STD - São Tomé and Príncipe Dobra",
			"SVC - El Salvador Colon",
			"SYP - Syria Pound",
			"SZL - Swaziland Lilangeni",
			"THB - Thailand Baht",
			"TJS - Tajikistan Somoni",
			"TMT - Turkmenistan Manat",
			"TND - Tunisia Dinar",
			"TOP - Tonga Pa'anga",
			"TRY - Turkey Lira",
			"TTD - Trinidad and Tobago Dollar",
			"TVD - Tuvalu Dollar",
			"TWD - Taiwan New Dollar",
			"TZS - Tanzania Shilling",
			"UAH - Ukraine Hryvnia",
			"UGX - Uganda Shilling",
			"USD - United States Dollar",
			"UYU - Uruguay Peso",
			"UZS - Uzbekistan Som",
			"VEF - Venezuela Bolivar",
			"VND - Viet Nam Dong",
			"VUV - Vanuatu Vatu",
			"WST - Samoa Tala",
			"XAF - Communauté Financière Africaine (BEAC) CFA Franc BEAC",
			"XCD - East Caribbean Dollar",
			"XDR - International Monetary Fund (IMF) Special Drawing Rights",
			"XOF - Communauté Financière Africaine (BCEAO) Franc",
			"XPF - Comptoirs Français du Pacifique (CFP) Franc",
			"YER - Yemen Rial",
			"ZAR - South Africa Rand",
			"ZMW - Zambia Kwacha",
			"ZWD - Zimbabwe Dollar"
		]
	end

	def status_color(status)
		case status
		when default_statuses[0]
		  'current-status-red'
		when default_statuses[1]
		  'current-status-yellow'
		when default_statuses[2]
		  'current-status-red'
		when default_statuses[3]
		  'current-status-green'
		end
	end

	def simpledate_format(date)
		date.strftime('%d-%m-%Y')
	end

	def date_format(date)
		date.strftime('%a, %d %B %Y')
	end

	def datetime_format(datetime)
		datetime.strftime('%a, %d %B %Y at %H:%M')
	end

	def monetary(value)
		'%.2f' % value
	end

	def currency_iso(currency)
		currency[0, 3]
	end

	def full_value(value, currency)
  	"#{monetary(value)} #{currency_iso(currency)}"
  end

	def distance(distance)
		"#{'%.1f' % distance} km"
	end

end